mutation removeSubscription($id: ID!, $action: SoftDeleteAction!) {
  removeSubscription(id: $id, action: $action) {
    id
  }
}

mutation setAccountDefaultLocation($accountId: ID!, $input: SetAccountDefaultLocationInput!) {
  setAccountDefaultLocation(accountId: $accountId, input: $input) {
    id
    defaultLocation {
      coordinates {
        lat
        lng
      }
      formattedAddress
      placeName
    }
  }
}

mutation editAccountDefaultLocation($accountId: ID!, $input: SetAccountDefaultLocationInput!, $asModeratorCorrection: Boolean) {
  editAccountDefaultLocation(accountId: $accountId, input: $input, asModeratorCorrection: $asModeratorCorrection) {
    id
    defaultLocation {
      coordinates {
        lat
        lng
      }
      formattedAddress
      placeName
    }
    hasPendingDefaultLocationReview
  }
}

mutation triggerAccountScrape($accountId: ID!) {
  triggerAccountScrape(accountId: $accountId) {
    triggered
    isInitialScrape
  }
}
