scalar JSON

enum EventType {
  EXHIBITION
  COMPETITION
  FESTIVAL
  PERFORMANCE
  WORKSHOP
  SEMINAR
  MARKET
  GATHERING
  PROMOTION
  FUNDRAISER
  CIVIC
  OTHER
}

enum EventCategory {
  MUSIC
  ARTS_AND_CULTURE
  FOOD_AND_DRINK
  SPORTS_AND_FITNESS
  FAMILY_AND_KIDS
  HOBBIES_AND_INTERESTS
  BUSINESS_AND_NETWORKING
  HEALTH_AND_WELLNESS
  HOLIDAY
  CHARITY_AND_CAUSES
  CIVIC_AND_COMMUNITY
  RELIGION_AND_SPIRITUALITY # Worship services, retreats, interfaith gatherings
  OTHER
}

type Coordinates {
  lat: Float!
  lng: Float!
}

type LocationDetails {
  coordinates: Coordinates!
  placeName: String
  placeId: String
  formattedAddress: String
  timezone: String
}

type Schedule {
  id: ID!
  eventId: ID!
  isMainSchedule: Boolean!
  eventStartDate: String!
  eventEndDate: String
  eventStartTime: String
  eventEndTime: String
  timezone: String
  performers: [String!]
  location: String
  locationDetails: LocationDetails
  ticketPrice: String
  ticketUrl: String
  registrationUrl: String
  updatedAt: String!
  createdAt: String!
  isAddedToCalendar: Boolean!
}

type Event {
  id: ID!
  eventName: String!
  slug: String!
  description: String
  types: [EventType!]
  categories: [EventCategory!]
  location: String
  sourceSocialMediaAccountId: ID
  postId: ID
  imageUrl: String
  sourcePostUrl: String
  originalPostUrl: String
  updatedAt: String!
  createdAt: String!
  schedules: [Schedule!]!
  isFavorited: Boolean!
  isAddedToCalendar: Boolean!
  sourceSocialMediaAccountProfile: SocialMediaAccountProfile
}

type EventConnection {
  items: [Event!]!
  hasMore: Boolean!
  totalCount: Int!
}

input EventQueryConditionInput {
  operator: String
  conditions: [EventQueryConditionInput!]
  field: String
  value: JSON
}

extend type Query {
  events(query: EventQueryConditionInput, limit: Int, offset: Int): EventConnection!
  event(id: ID!): Event
  eventBySlug(slug: String!): Event
}
