type SocialMediaAccountProfile {
  id: ID!
  accountId: String!
  platform: String!
  displayName: String!
  username: String!
  profileImageUrl: String
  description: String
  lastPostDate: String
  lastScrapedAt: String
  isScrapeInProgress: Boolean!
  defaultLocation: LocationDetails
  hasPendingDefaultLocationReview: Boolean!
  accountType: String
  accountTypeStatus: String
}

extend type Query {
  socialMediaAccountProfileByAccountId(
    platform: String!
    accountId: String!
  ): SocialMediaAccountProfile
}

input SetAccountDefaultLocationInput {
  placeId: String
  latitude: Float
  longitude: Float
}

extend type Mutation {
  setAccountDefaultLocation(accountId: ID!, input: SetAccountDefaultLocationInput!): SocialMediaAccountProfile!
  editAccountDefaultLocation(accountId: ID!, input: SetAccountDefaultLocationInput!, asModeratorCorrection: Boolean): SocialMediaAccountProfile!
}
