type Subscription {
  id: ID!
  accountId: ID!
  isNewlyAdded: Boolean!
  createdAt: String!
  account: SocialMediaAccountProfile!
}

extend type Query {
  mySubscriptions: [Subscription!]!
}

input SubscribeToAccountInput {
  platform: String!
  accountId: String!
  username: String!
  displayName: String!
}

type SubscribeToAccountResult {
  subscription: Subscription!
  alreadySubscribed: Boolean!
}

extend type Mutation {
  subscribeToAccount(input: SubscribeToAccountInput!): SubscribeToAccountResult!
  removeSubscription(id: ID!, action: SoftDeleteAction!): Subscription!
}
