type Subscription {
  id: ID!
  accountId: ID!
  isNewlyAdded: Boolean!
  createdAt: String!
  account: SocialMediaAccountProfile!
  pendingExtractionCount: Int!
  isInactive: Boolean!
}

extend type Query {
  mySubscriptions: [Subscription!]!
}

input SubscribeToAccountInput {
  platform: String!
  accountId: String!
  username: String!
  displayName: String!
}

type SubscribeToAccountResult {
  subscription: Subscription!
  alreadySubscribed: Boolean!
}

type TriggerAccountScrapeResult {
  triggered: Boolean!
  isInitialScrape: Boolean!
}

extend type Mutation {
  subscribeToAccount(input: SubscribeToAccountInput!): SubscribeToAccountResult!
  removeSubscription(id: ID!, action: SoftDeleteAction!): Subscription!
  markSubscriptionViewed(subscriptionId: ID!): Subscription!
  triggerAccountScrape(accountId: ID!): TriggerAccountScrapeResult!
}
