enum WidgetDisplayMode {
  CARD
  CALENDAR
}

enum WidgetTheme {
  DARK
  LIGHT
}

type Widget {
  id: ID!
  ownerUserId: ID!
  filters: EventFilter!
  displayMode: WidgetDisplayMode!
  theme: WidgetTheme!
  createdAt: String!
  deletedAt: String
}

input CreateWidgetInput {
  filters: EventFilterInput!
  displayMode: WidgetDisplayMode
  theme: WidgetTheme
}

input UpdateWidgetInput {
  filters: EventFilterInput
  displayMode: WidgetDisplayMode
  theme: WidgetTheme
}

extend type Query {
  myWidgets: [Widget!]!
  widgetById(id: ID!): Widget
}

extend type Mutation {
  createWidget(input: CreateWidgetInput!): Widget!
  updateWidget(id: ID!, input: UpdateWidgetInput!): Widget!
  deleteWidget(id: ID!, action: SoftDeleteAction!): Widget!
}
