query getMyLocations {
  myLocations {
    id
    name
    locationDetails {
      formattedAddress
      placeName
      coordinates {
        lat
        lng
      }
    }
    radius
    createdAt
    updatedAt
  }
}

query addressAutocomplete($input: String!) {
  addressAutocomplete(input: $input) {
    placeId
    description
  }
}

query previewLocation($latitude: Float!, $longitude: Float!) {
  previewLocation(latitude: $latitude, longitude: $longitude) {
    formattedAddress
    placeName
    coordinates {
      lat
      lng
    }
    provider
  }
}
