mutation toggleFavorite($eventId: ID!) {
  toggleFavorite(eventId: $eventId) {
    eventId
    isFavorited
  }
}

mutation toggleCalendarAddition($eventId: ID!, $scheduleId: ID!) {
  toggleCalendarAddition(eventId: $eventId, scheduleId: $scheduleId) {
    eventId
    scheduleId
    isAddedToCalendar
  }
}

mutation resolveScheduleTimezone($scheduleId: ID!, $timezone: String!) {
  resolveScheduleTimezone(scheduleId: $scheduleId, timezone: $timezone) {
    scheduleId
    timezone
    timezoneStatus
  }
}
