query getEvents($limit: Int, $offset: Int, $query: EventQueryConditionInput) {
  events(limit: $limit, offset: $offset, query: $query) {
    items {
      id
      eventName
      slug
      isFavorited
      imageUrl
      location
      types
      categories
      schedules {
        id
        isMainSchedule
        eventStartDate
        ticketPrice
      }
    }
    hasMore
    totalCount
  }
}

query getFavoritedEventIds($query: EventQueryConditionInput) {
  events(query: $query) {
    items {
      id
    }
    totalCount
  }
}

query getEventBySlug($slug: String!) {
  eventBySlug(slug: $slug) {
    id
    eventName
    slug
    description
    location
    types
    categories
    imageUrl
    sourcePostUrl
    originalPostUrl
    isFavorited
    schedules {
      id
      isMainSchedule
      eventStartDate
      isAddedToCalendar
      eventEndDate
      eventStartTime
      eventEndTime
      performers
      location
      locationDetails {
        coordinates {
          lat
          lng
        }
        placeName
        placeId
        formattedAddress
        timezone
      }
      ticketPrice
      ticketUrl
      registrationUrl
    }
  }
}

query getEventForIcsExport($id: ID!) {
  event(id: $id) {
    id
    eventName
    slug
    description
    location
    schedules {
      id
      eventStartDate
      eventEndDate
      eventStartTime
      eventEndTime
      timezone
      location
      locationDetails {
        formattedAddress
      }
    }
  }
}

query getEventsForCalendar($limit: Int, $offset: Int, $query: EventQueryConditionInput) {
  events(limit: $limit, offset: $offset, query: $query) {
    items {
      id
      eventName
      slug
      imageUrl
      location
      types
      categories
      schedules {
        id
        isMainSchedule
        eventStartDate
        eventEndDate
        eventStartTime
        eventEndTime
        ticketPrice
      }
    }
    hasMore
    totalCount
  }
}
